# Manifest file for product Deployment

apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-dev
  template:
    metadata:
      labels:
        app: product-dev
    spec:
      containers:
      - name: product-dev
        image: DIT

---
apiVersion: v1
kind: Service
metadata:
  name: product-dev-svc
spec:
  selector:
    app: product-dev
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8761